# Generated by Django 3.2.6 on 2021-09-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0002_ability_chant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chant',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='chant',
            name='card_ptr',
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Chant',
        ),
    ]
