# Generated by Django 3.2.6 on 2021-09-01 11:42

import cardDatabase.models.Effects
from django.db import migrations, models
import django.db.models.deletion
import game.models.Event


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cardDatabase', '0003_auto_20210901_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomaticAbilityTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivateAbility',
            fields=[
                ('ability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardDatabase.ability')),
            ],
            options={
                'abstract': False,
            },
            bases=('cardDatabase.ability',),
        ),
        migrations.CreateModel(
            name='ContinuousAbility',
            fields=[
                ('ability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardDatabase.ability')),
            ],
            options={
                'abstract': False,
            },
            bases=('cardDatabase.ability',),
        ),
        migrations.CreateModel(
            name='OneTimeEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_type_id', models.PositiveIntegerField()),
                ('event_type_type', models.ForeignKey(limit_choices_to=game.models.Event.GameEvent.get_type_choices, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardDatabase.card')),
                ('effect_type_id', models.PositiveIntegerField()),
                ('abilities', models.ManyToManyField(to='cardDatabase.Ability')),
                ('effect_type_type', models.ForeignKey(limit_choices_to=cardDatabase.models.Effects.Effect.get_type_choices, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            bases=('cardDatabase.card',),
        ),
        migrations.CreateModel(
            name='AutomaticAbility',
            fields=[
                ('ability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardDatabase.ability')),
                ('triggered_count', models.IntegerField(default=0)),
                ('trigger', models.ManyToManyField(to='cardDatabase.AutomaticAbilityTrigger')),
            ],
            options={
                'abstract': False,
            },
            bases=('cardDatabase.ability',),
        ),
    ]
