# Generated by Django 3.2.6 on 2021-09-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0004_ability_activateability_automaticability_automaticabilitytrigger_card_chant_continuousability_onetim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automaticabilitytrigger',
            name='id',
        ),
        migrations.AddField(
            model_name='automaticabilitytrigger',
            name='ability_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardDatabase.ability'),
            preserve_default=False,
        ),
    ]
