# Generated by Django 3.2.6 on 2021-09-21 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0005_auto_20210902_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Regalia', 'Regalia'), ('Chant', 'Chant'), ('Rune', 'Rune'), ('Master Rune', 'Master Rune'), ('Magic Stone', 'Magic Stone'), ('Basic Magic StoneSpecial Magic Stone', 'Basic Magic StoneSpecial Magic Stone'), ('True Magic StoneRuler', 'True Magic StoneRuler'), ('Basic J-Ruler', 'Basic J-Ruler'), ('J-RulerSpell:Chant-Standby', 'J-RulerSpell:Chant-Standby')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='chant',
            name='card_ptr',
        ),
        migrations.AddField(
            model_name='card',
            name='ATK',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='DEF',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='divinity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='flavour',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare'), ('T', 'Token'), ('MR', 'Marvel Rare'), ('RR', 'Ruler'), ('JR', 'J-Ruler'), ('JR*', 'Colossal J-Ruler'), ('N', 'Normal'), ('SEC', 'Secret Rare'), ('AR', 'Ascended Ruler'), ('JAR', 'Ascended J-ruler')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chant',
            name='card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.card'),
            preserve_default=False,
        ),
        
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.cluster')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='ability_texts',
            field=models.ManyToManyField(related_name='ability_texts', to='cardDatabase.AbilityText'),
        ),
        migrations.AddField(
            model_name='card',
            name='races',
            field=models.ManyToManyField(related_name='races', to='cardDatabase.Race'),
        ),
        migrations.AddField(
            model_name='card',
            name='types',
            field=models.ManyToManyField(related_name='types', to='cardDatabase.Type'),
        ),
    ]
