# Generated by Django 3.2.6 on 2021-09-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0006_auto_20210922_0109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chant',
        ),
    ]
