# Generated by Django 3.2.6 on 2021-09-21 13:14

import cardDatabase.models.Effects
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cardDatabase', '0007_delete_chant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type_id', models.PositiveIntegerField()),
                ('abilities', models.ManyToManyField(to='cardDatabase.Ability')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.card')),
                ('effect_type_type', models.ForeignKey(limit_choices_to=cardDatabase.models.Effects.Effect.get_type_choices, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
