# Generated by Django 3.2.6 on 2021-09-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0008_chant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chant',
            name='abilities',
        ),
    ]
