# Generated by Django 3.2.6 on 2021-10-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0009_remove_chant_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name_without_punctuation',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Regalia', 'Regalia'), ('Chant', 'Chant'), ('Rune', 'Rune'), ('Master Rune', 'Master Rune'), ('Magic Stone', 'Magic Stone'), ('Basic Magic Stone', 'Basic Magic Stone'), ('Special Magic Stone', 'Special Magic Stone'), ('True Magic Stone', 'True Magic Stone'), ('Ruler', 'Ruler'), ('Basic J-Ruler', 'Basic J-Ruler'), ('J-RulerSpell:Chant-Standby', 'J-RulerSpell:Chant-Standby'), ('Resonator', 'Resonator')], max_length=200),
        ),
    ]
