# Generated by Django 3.2.6 on 2021-10-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0010_auto_20211023_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ATK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='DEF',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
