# Generated by Django 3.2.6 on 2021-10-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0011_auto_20211023_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='divinity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavour',
            field=models.TextField(blank=True, null=True),
        ),
    ]
