# Generated by Django 3.2.6 on 2021-11-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0012_auto_20211026_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cards'),
        ),
    ]
