# Generated by Django 3.2.6 on 2021-11-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ability_texts',
            field=models.ManyToManyField(blank=True, related_name='ability_texts', to='cardDatabase.AbilityText'),
        ),
        migrations.AlterField(
            model_name='card',
            name='races',
            field=models.ManyToManyField(blank=True, related_name='races', to='cardDatabase.Race'),
        ),
    ]
