# Generated by Django 3.2.6 on 2021-11-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0016_auto_20211118_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('db_representation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='colours',
            field=models.ManyToManyField(related_name='cards', to='cardDatabase.CardColour'),
        ),
    ]
