# Generated by Django 3.2.6 on 2021-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0017_auto_20211122_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ability_texts',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cardDatabase.AbilityText'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare'), ('T', 'Token'), ('MR', 'Marvel Rare'), ('RR', 'Ruler'), ('JR', 'J-Ruler'), ('JR*', 'Colossal J-Ruler'), ('N', 'Normal'), ('AR', 'Ascended Ruler'), ('JAR', 'Ascended J-ruler')], max_length=200),
        ),
    ]
