# Generated by Django 3.2.6 on 2021-11-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0017_auto_20211122_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DeckListCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.card')),
                ('decklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cardDatabase.decklist')),
            ],
        ),
    ]
