# Generated by Django 3.2.6 on 2021-11-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0018_decklist_decklistcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckListZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('added_by_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='decklistcard',
            name='zone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.decklistzone'),
            preserve_default=False,
        ),
    ]
