# Generated by Django 3.2.6 on 2021-11-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0020_decklistzone_show_by_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decklistzone',
            name='added_by_user',
        ),
    ]
