# Generated by Django 3.2.6 on 2021-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0021_remove_decklistzone_added_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklistcard',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
