# Generated by Django 3.2.6 on 2021-11-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0018_auto_20211125_0105'),
        ('cardDatabase', '0022_decklistcard_quantity'),
    ]

    operations = [
    ]
