# Generated by Django 3.2.6 on 2022-02-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0019_keyword'),
        ('cardDatabase', '0023_merge_20211125_0142'),
    ]

    operations = [
    ]
