# Generated by Django 3.2.6 on 2022-02-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0024_merge_0019_keyword_0023_merge_20211125_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklist',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-09 02:15'),
            preserve_default=False,
        ),
    ]
