# Generated by Django 3.2.6 on 2022-03-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0025_decklist_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeckListZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('decklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.decklist')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.decklistzone')),
            ],
        ),
        migrations.AlterField(
            model_name='decklistcard',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.userdecklistzone'),
        ),
    ]
