# Generated by Django 3.2.6 on 2022-03-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0026_auto_20220305_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklistzone',
            name='position',
            field=models.IntegerField(default=99999),
            preserve_default=False,
        ),
    ]
