# Generated by Django 3.2.6 on 2022-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0027_decklistzone_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdecklistzone',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
