# Generated by Django 3.2.6 on 2022-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0028_alter_userdecklistzone_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decklistzone',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdecklistzone',
            name='position',
            field=models.IntegerField(default=99999),
            preserve_default=False,
        ),
    ]
