# Generated by Django 3.2.6 on 2022-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0029_auto_20220305_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklist',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
