# Generated by Django 3.2.6 on 2022-05-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0032_auto_20220504_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1)),
                ('ability_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cardDatabase.abilitytext')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='cardDatabase.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='ability_text',
            field=models.ManyToManyField(blank=True, related_name='crds', through='cardDatabase.CardAbility', to='cardDatabase.AbilityText'),
        ),
    ]
