# Generated by Django 3.2.6 on 2022-05-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0033_auto_20220514_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='ability_texts',
        ),
    ]
