# Generated by Django 3.2.6 on 2022-05-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0034_remove_card_ability_texts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='ability_text',
            new_name='ability_texts',
        ),
    ]
