# Generated by Django 3.2.6 on 2022-05-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0035_rename_ability_text_card_ability_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ability_texts',
            field=models.ManyToManyField(blank=True, related_name='cards', through='cardDatabase.CardAbility', to='cardDatabase.AbilityText'),
        ),
    ]
