# Generated by Django 3.2.6 on 2022-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0036_alter_card_ability_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklist',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
