# Generated by Django 3.2.6 on 2022-06-07 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0037_decklist_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CombinationBannedCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(related_name='cards', to='cardDatabase.Card')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.format')),
            ],
        ),
        migrations.CreateModel(
            name='BannedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.card')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.format')),
            ],
        ),
    ]
