# Generated by Django 3.2.6 on 2022-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0040_ruling'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruling',
            name='company_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
