# Generated by Django 3.2.6 on 2022-11-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0041_ruling_company_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('all_time', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MostPickedCardPickRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.card')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.pickperiod')),
            ],
        ),
        migrations.CreateModel(
            name='CardTypePickRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.type')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.pickperiod')),
            ],
        ),
        migrations.CreateModel(
            name='CardTotalCostPickRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.pickperiod')),
            ],
        ),
        migrations.CreateModel(
            name='AttributePickRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('card_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.cardcolour')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.pickperiod')),
            ],
        ),
    ]
