# Generated by Django 3.2.6 on 2023-08-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0045_alter_card_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('technical_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.restrictionaction')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardDatabase.profile')),
                ('restricted_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.tag')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_tag', to='cardDatabase.tag')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cardDatabase.Tag'),
        ),
    ]
