# Generated by Django 3.2.6 on 2023-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0047_auto_20230808_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklist',
            name='shareCode',
            field=models.TextField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='decklist',
            name='shareMode',
            field=models.TextField(blank=True, default='', max_length=32, null=True),
        ),
    ]
