# Generated by Django 3.2.6 on 2024-07-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0049_auto_20240126_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('identifier', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cardability',
            name='special_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardDatabase.abilitystyle'),
        ),
    ]
