# Generated by Django 3.2.6 on 2024-07-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0049_auto_20240126_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardartist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='decklist',
            name='deck_type',
            field=models.CharField(choices=[['Wanderer', 'Wanderer'], ['ABC', 'ABC'], ['Custom', 'Custom']], default='Wanderer', max_length=32),
        ),
    ]
