# Generated by Django 3.2.6 on 2024-07-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0049_auto_20240126_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostpickedcardpickrate',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularities', to='cardDatabase.card'),
        ),
    ]
