# Generated by Django 3.2.6 on 2024-08-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0050_auto_20240711_1955'),
        ('cardDatabase', '0051_auto_20240725_1705'),
    ]

    operations = [
    ]
