# Generated by Django 3.2.6 on 2024-11-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0050_auto_20240729_1810'),
        ('cardDatabase', '0052_merge_0050_auto_20240711_1955_0051_auto_20240725_1705'),
    ]

    operations = [
    ]
