# Generated by Django 3.2.6 on 2025-01-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0056_alter_card_rarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_image',
            new_name='_card_image',
        ),
    ]
