# Generated by Django 3.2.6 on 2024-12-20 07:17

import cardDatabase.models.Banlist
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0056_alter_card_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='decklist',
            name='deck_format',
            field=models.ForeignKey(default=cardDatabase.models.Banlist.Format.get_default, on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.format'),
        ),
    ]
