# Generated by Django 3.2.6 on 2025-02-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0057_decklist_deck_format'),
        ('cardDatabase', '0057_rename_card_image_card__card_image'),
    ]

    operations = [
    ]
