# Generated by Django 3.2.6 on 2025-02-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0058_merge_20250208_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decklistzone',
            name='format',
        ),
        migrations.AddField(
            model_name='decklistzone',
            name='formats',
            field=models.ManyToManyField(related_name='formats', to='cardDatabase.Format'),
        ),
    ]
