# Generated by Django 3.2.6 on 2025-01-09 17:33

from django.db import migrations, models
from fowsim import constants as CONS


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0058_merge_20250208_1750'),
    ]

    def updateLockFromShareMode(apps, schema_editor):
        DeckLists = apps.get_model('cardDatabase', 'DeckList')
        for row in DeckLists.objects.all():
            if row.shareMode == CONS.MODE_TOURNAMENT:
                row.deck_lock = CONS.MODE_PRIVATE
                #update share mode to also be private letting the user still manage his lock state
                #tournament is reserved for tournaments only not for the user to change
                row.shareMode = CONS.MODE_PRIVATE
                row.save()

    operations = [
        migrations.AddField(
            model_name='decklist',
            name='deck_lock',
            field=models.TextField(blank=True, choices=[['private', 'private'], ['tournament', 'tournament']], default=None, max_length=32, null=True),
        ),
         migrations.RunPython(updateLockFromShareMode),
    ]
