# Generated by Django 3.2.6 on 2025-01-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0058_decklist_deck_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_data', models.JSONField()),
                ('is_online', models.BooleanField(default=False)),
                ('registration_deadline', models.DateTimeField()),
                ('registration_locked', models.BooleanField(default=False)),
                ('deck_edit_deadline', models.DateTimeField()),
                ('deck_edit_locked', models.BooleanField(default=False)),
                ('tournament_finished', models.BooleanField(default=False)),
                ('reveal_decklists', models.BooleanField(default=False)),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardDatabase.format')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
                ('hint', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.profile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.staffrole')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.TextField(blank=True, choices=[['requested', 'requested'], ['accepted', 'accepted'], ['completed', 'completed']], default=None, max_length=32, null=True)),
                ('user_data', models.JSONField()),
                ('notes', models.CharField(max_length=500)),
                ('standing', models.IntegerField()),
                ('dropped_out', models.BooleanField(default=False)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.decklist')),
                ('last_registration_updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardDatabase.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_player', to='cardDatabase.profile')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDatabase.tournamentlevel'),
        ),
    ]
