# Generated by Django 5.1.6 on 2025-04-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0059_auto_20250219_1658'),
        ('cardDatabase', '0059_auto_20250225_1734'),
    ]

    operations = [
    ]
