# Generated by Django 3.2.6 on 2025-03-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0060_tournament_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='cardDatabase.tournament'),
        ),
    ]
