# Generated by Django 3.2.6 on 2025-04-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0060_merge_0059_auto_20250219_1658_0059_auto_20250225_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare'), ('XR', 'Extension Rare'), ('T', 'Token'), ('MR', 'Marvel Rare'), ('RR', 'Ruler'), ('JR', 'J-Ruler'), ('JR*', 'Colossal J-Ruler'), ('N', 'Normal'), ('SEC', 'Secret Rare'), ('AR', 'Ascended Ruler'), ('JAR', 'Ascended J-ruler'), ('SRR', 'Sub-ruler')], max_length=200),
        ),
    ]
