# Generated by Django 3.2.6 on 2025-04-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0060_merge_0059_auto_20250219_1658_0059_auto_20250225_1734'),
        ('cardDatabase', '0061_alter_tournamentplayer_tournament'),
    ]

    operations = [
    ]
