# Generated by Django 3.2.6 on 2025-04-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0061_alter_card_rarity'),
        ('cardDatabase', '0062_merge_20250410_1951'),
    ]

    operations = [
    ]
