# Generated by Django 3.2.6 on 2025-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0063_merge_0061_alter_card_rarity_0062_merge_20250410_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
