# Generated by Django 3.2.6 on 2025-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0064_alter_tournamentplayer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_create_tournament',
            field=models.BooleanField(default=True),
        ),
    ]
