# Generated by Django 5.1.6 on 2025-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0066_auto_20250716_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='see_debug_toolbar',
            field=models.BooleanField(default=False),
        ),
    ]
