# Generated by Django 5.1.6 on 2025-11-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0067_see_debug_toolbar'),
        ('cardDatabase', '0068_alter_type_name'),
    ]

    operations = [
    ]
