# Generated by Django 5.1.6 on 2025-11-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0069_merge_0067_see_debug_toolbar_0068_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare'), ('XR', 'Extension Rare'), ('T', 'Token'), ('MR', 'Marvel Rare'), ('RR', 'Ruler'), ('JR', 'J-Ruler'), ('JR*', 'Colossal J-Ruler'), ('N', 'Normal'), ('SEC', 'Secret Rare'), ('AR', 'Ascended Ruler'), ('JAR', 'Ascended J-ruler'), ('SRR', 'Sub-Ruler')], max_length=200),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Regalia', 'Regalia'), ('Chant', 'Chant'), ('Rune', 'Rune'), ('Master Rune', 'Master Rune'), ('Magic Stone', 'Magic Stone'), ('Basic Magic Stone', 'Basic Magic Stone'), ('Special Magic Stone', 'Special Magic Stone'), ('True Magic Stone', 'True Magic Stone'), ('Ruler', 'Ruler'), ('Basic J-Ruler', 'Basic J-Ruler'), ('J-Ruler', 'J-Ruler'), ('Spell:Chant-Standby', 'Spell:Chant-Standby'), ('Resonator', 'Resonator'), ('Sub-Ruler', 'Sub-Ruler'), ('Extension Rule', 'Extension Rule'), ('Warden', 'Warden'), ('Darkness Magic Stone', 'Darkness Magic Stone'), ('Fire Magic Stone', 'Fire Magic Stone'), ('Light Magic Stone', 'Light Magic Stone'), ('Water Magic Stone', 'Water Magic Stone'), ('Wind Magic Stone', 'Wind Magic Stone'), ('Void Magic Stone', 'Void Magic Stone')], max_length=200),
        ),
    ]
