# Generated by Django 5.1.6 on 2026-01-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0070_alter_card_rarity_alter_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardartist',
            name='connected_artists',
            field=models.ManyToManyField(blank=True, help_text='Other artist names (pen names) that refer to the same person', related_name='related_artists', to='cardDatabase.cardartist'),
        ),
    ]
