# Generated by Django 3.2.6 on 2022-07-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardDatabase', '0038_bannedcard_combinationbannedcards_format'),
        ('cardDatabase', '0099_collection_collectioncard'),
    ]

    operations = [
    ]
