# Generated by Django 3.2.6 on 2021-09-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210826_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_zone', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='zones',
        ),
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MoveCard',
            fields=[
                ('gameevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.gameevent')),
                ('from_area', models.ManyToManyField(related_name='from_area', to='game.Area')),
                ('to_area', models.ManyToManyField(related_name='to_area', to='game.Area')),
            ],
            options={
                'abstract': False,
            },
            bases=('game.gameevent',),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='losers',
            field=models.ManyToManyField(related_name='losers', to='game.Player'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='winners',
            field=models.ManyToManyField(related_name='winners', to='game.Player'),
        ),
    ]
