# Generated by Django 3.2.6 on 2021-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210901_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='zones',
            field=models.ManyToManyField(to='game.Area'),
        ),
    ]
