# Generated by Django 3.2.6 on 2021-09-07 11:24

import cardDatabase.models.CardType
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('game', '0004_game_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.area')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.PositiveIntegerField()),
                ('card_type', models.ForeignKey(limit_choices_to=cardDatabase.models.CardType.Card.get_type_choices, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('game_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamearea')),
            ],
        ),
    ]
