# Generated by Django 3.2.6 on 2021-09-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamearea_gamecard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoveCard',
            new_name='MoveCardFromPosition',
        ),
    ]
