# Generated by Django 3.2.6 on 2021-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_movecard_movecardfromposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='movecardfromposition',
            name='from_position',
            field=models.TextField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('X From Top', 'X From Top'), ('X From Bottom', 'X From Bottom'), ("Player's Choice", "Player's Choice")], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movecardfromposition',
            name='to_position',
            field=models.TextField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('X From Top', 'X From Top'), ('X From Bottom', 'X From Bottom'), ("Player's Choice", "Player's Choice")], default=''),
            preserve_default=False,
        ),
    ]
