# Generated by Django 3.2.6 on 2021-09-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210908_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movecardfromposition',
            name='from_position',
            field=models.TextField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('X From Top', 'X From Top'), ('X From Bottom', 'X From Bottom'), ("Player's Choice", "Player's Choice"), ('Unordered', 'Unordered')]),
        ),
        migrations.AlterField(
            model_name='movecardfromposition',
            name='to_position',
            field=models.TextField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('X From Top', 'X From Top'), ('X From Bottom', 'X From Bottom'), ("Player's Choice", "Player's Choice"), ('Unordered', 'Unordered')]),
        ),
    ]
