# Generated by Django 3.2.6 on 2021-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210908_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='movecardfromposition',
            name='from_controller',
            field=models.TextField(choices=[("Effect's Controller", "Effect's Controller"), ("Effect's Controller's Opponent", "Effect's Controller's Opponent")], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movecardfromposition',
            name='to_controller',
            field=models.TextField(choices=[("Effect's Controller", "Effect's Controller"), ("Effect's Controller's Opponent", "Effect's Controller's Opponent")], default=1),
            preserve_default=False,
        ),
    ]
