CARD_POSITION_TOP = 'Top'
CARD_POSITION_BOTTOM = 'Bottom'
CARD_POSITION_X_FROM_TOP = "X From Top"
CARD_POSITION_X_FROM_BOTTOM = "X From Bottom"
CARD_POSITION_PLAYERS_CHOICE = "Player's Choice"
CARD_POSITION_UNORDERED_AREA = "Unordered"

MOVE_CARD_POSITION_CHOICES_VALUES = [
    CARD_POSITION_TOP,
    CARD_POSITION_BOTTOM,
    CARD_POSITION_X_FROM_TOP,
    CARD_POSITION_X_FROM_BOTTOM,
    CARD_POSITION_PLAYERS_CHOICE,
    CARD_POSITION_UNORDERED_AREA,
]


EFFECT_AREA_EFFECT_CONTROLLER = "Effect's Controller"
EFFECT_AREA_EFFECT_CONTROLLER_OPPONENT = "Effect's Controller's Opponent"
EFFECT_AREA_CHOICES_VALUES = [
    EFFECT_AREA_EFFECT_CONTROLLER,
    EFFECT_AREA_EFFECT_CONTROLLER_OPPONENT,
]

RARITY_COMMON = 'Common'
RARITY_UNCOMMON = 'Uncommon'
RARITY_RARE = 'Rare'
RARITY_SUPER_RARE = 'Super Rare'
RARITY_TOKEN = 'Token'
RARITY_MARVEL_RARE = 'Marvel Rare'
RARITY_RULER = 'Ruler'
RARITY_J_RULER = 'J-Ruler'
RARITY_COLOSSAL_J_RULER = 'Colossal J-Ruler'
RARITY_NORMAL = 'Normal'
RARITY_SECRET_RARE = 'Secret Rare'
RARITY_ASCENDED_RULER = 'Ascended Ruler'
RARITY_ASCENDED_J_RULER = 'Ascended J-ruler'

RARITY_COMMON_VALUE = 'C'
RARITY_UNCOMMON_VALUE = 'U'
RARITY_RARE_VALUE = 'R'
RARITY_SUPER_RARE_VALUE = 'SR'
RARITY_TOKEN_VALUE = 'T'
RARITY_MARVEL_RARE_VALUE = 'MR'
RARITY_RULER_VALUE = 'RR'
RARITY_J_RULER_VALUE = 'JR'
RARITY_COLOSSAL_J_RULER_VALUE = 'JR*'
RARITY_NORMAL_VALUE = 'N'
RARITY_SECRET_RARE_VALUE = 'SEC'
RARITY_ASCENDED_RULER_VALUE = 'AR'
RARITY_ASCENDED_J_RULER_VALUE = 'JAR'

RARITY_CHOICE_VALUES = (
    (RARITY_COMMON_VALUE, RARITY_COMMON),
    (RARITY_UNCOMMON_VALUE, RARITY_UNCOMMON),
    (RARITY_RARE_VALUE, RARITY_RARE),
    (RARITY_SUPER_RARE_VALUE, RARITY_SUPER_RARE),
    (RARITY_TOKEN_VALUE, RARITY_TOKEN),
    (RARITY_MARVEL_RARE_VALUE, RARITY_MARVEL_RARE),
    (RARITY_RULER_VALUE, RARITY_RULER),
    (RARITY_J_RULER_VALUE, RARITY_J_RULER),
    (RARITY_COLOSSAL_J_RULER_VALUE, RARITY_COLOSSAL_J_RULER),
    (RARITY_NORMAL_VALUE, RARITY_NORMAL),
    (RARITY_SECRET_RARE_VALUE, RARITY_SECRET_RARE),
    (RARITY_ASCENDED_RULER_VALUE, RARITY_ASCENDED_RULER),
    (RARITY_ASCENDED_J_RULER_VALUE, RARITY_ASCENDED_J_RULER)
)

CARD_TYPE_VALUES = [
    'Regalia',
    'Chant',
    'Rune',
    'Master Rune',
    'Magic Stone',
    'Basic Magic Stone'
    'Special Magic Stone',
    'True Magic Stone'
    'Ruler',
    'Basic J-Ruler',
    'J-Ruler'
    'Spell:Chant-Standby',
]
CARD_SUBTYPE_VALUES = [
    'J',
    'Resonator',
    'Field',
    'Chant-Instant',
    'Stranger',
    'Shift'
]

FIRE_NAME = 'Fire'
WATER_NAME = 'Water'
DARKNESS_NAME = 'Darkness'
WIND_NAME = 'Wind'
LIGHT_NAME = 'Light'
VOID_NAME = 'Void'

ATTRIBUTE_NAMES = [
    FIRE_NAME,
    WATER_NAME,
    DARKNESS_NAME,
    WIND_NAME,
    LIGHT_NAME
]

ATTRIBUTE_FIRE_CODE = 'F'
ATTRIBUTE_WATER_CODE = 'U'
ATTRIBUTE_DARKNESS_CODE = 'B'
ATTRIBUTE_LIGHT_CODE = 'W'
ATTRIBUTE_WIND_CODE = 'G'
ATTRIBUTE_VOID_CODE = 'V'

DOUBLE_SIDED_CARD_CHARACTER = '^'

FOWTCG_CARD_DATABASE_SET_INDEX = {
    'CMF': 11,
    'TAT': 16,
    'MPR': 17,
    'MOA': 18,
    'VIN001': 19,
    'VS01': 7,
    'SKL': 8,
    'TTW': 9,
    'TMS': 13,
    'BFA': 14,
    'VIN002': 15,
    'SDL1': 3,
    'SDL2': 3,
    'SDL3': 3,
    'SDL4': 3,
    'SDL5': 3,
    'CFC': 2,
    'LEL': 4,
    'VIN003': 6,
    'RDE': 26,
    'ENW': 28,
    'SDR1': 29,
    'SDR2': 29,
    'SDR3': 29,
    'SDR4': 29,
    'SDR5': 29,
    'ACN': 30,
    'ADK': 31,
    'TSW': 34,
    'SDR6': 33,
    'WOM': 35,
    'SDV1': 38,
    'SDV2': 38,
    'SDV3': 38,
    'SDV4': 38,
    'SDV5': 38,
    'NDR': 37,
    'SNV': 39,
    'AOA': 40,
    'DBV': 41,
    'SDAO1': 43,
    'AO1': 42,
    'SDAO2': 45,
    'AO2': 44,
    'GITS2045SD': 47,
    'GITS2045': 48,
    'AO3': 46,
    'POFA': 49,
    'EDL': 50,
    'MSW': 51,
    'ROL': 52,
    'ADW': 53,
    'TST': 54,
    'PR': 20
}